services:

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /mnt/data/docker/media/prowlarr:/config
    networks:
      - media
      - nginx
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /mnt/data/docker/media/radarr:/config
      - /mnt/data/media/movies:/movies
      - /mnt/data/media/animov:/animov
      - /mnt/data/media/completed:/downloads
    networks:
      - media
      - nginx
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /mnt/data/docker/media/sonarr:/config
      - /mnt/data/media/tv:/tv
      - /mnt/data/media/anime:/anime
      - /mnt/data/media/completed:/downloads
    networks:
      - media
      - nginx
    restart: unless-stopped

  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /mnt/data/docker/media/lidarr:/config
      - /mnt/data/media/music:/music
      - /mnt/data/media/completed:/downloads
    networks:
      - media
      - nginx
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    networks:
      - media
      - nginx
    volumes:
      - /mnt/data/docker/media/bazarr:/config
      - /mnt/data/media:/media
    restart: unless-stopped



  qbittorrent:
    image: linuxserver/qbittorrent:amd64-5.1.0-libtorrentv1
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - WEBUI_PORT=8081
    volumes:
      - /mnt/data/docker/media/qbit:/config
      - /mnt/data/media/completed:/downloads
    networks:
      - media
      - nginx
    ports:
      - 8081:8081
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /mnt/data/docker/media/jellyfin:/config
      - /mnt/data/media:/media
    networks:
      - media
      - nginx
    restart: unless-stopped

networks:
  media:
    external: true
  nginx:
    external: true

